[project]
name = "py-rust-stemmers"
version = "0.1.1"
description = "A short description of your package"

# Include a long description
readme = "README.md"
readme-content-type = "text/markdown"  # Or "text/x-rst" if using reStructuredText
