name: Publish

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.1
      - name: Install maturin
        run: pip install maturin
      - name: Build and publish
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          maturin publish --username __token__ --password $MATURIN_PASSWORD --target aarch64-unknown-linux-gnu --zig